### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by acholt** [jasonc/chef-ovirt#7]
Hi Jason

Hope you are well.

I haven't seem any activity on this repository for a while. I would be happy to continue maintaining it if you no longer wish too?

Regards,
Andrew

**Comment by jasonc** [comment]
Sounds good to me as I haven't worked on this project in quite some time.  I've sent an invitation to you to   collaborate.  Thanks!

**Comment by acholt** [comment]
Thanks Jason.

Could you add me as a collaborator on Chef Supermarket so I can update it. My profile is 
https://supermarket.chef.io/users/andrewholt

Many Thanks,
Andrew

**Comment by jasonc** [comment]
I added you on as a collaborator on Chef Supermarket too.

**Comment by acholt** [comment]
Awesome! :-)

Thanks Jason
